### ISSUE TITLE
Perform the same warp on another picture

### ISSUE THREAD

**Issue by SZUHvern** [SteffenCzolbe/pyLDDMM#6]
Hi, Steffen!
Thanks for your efforts to compile the Python version of LDDMM.
I want to know if I have completed the iteration using a pair of pictures, how should I apply another picture to perform the same warp?

**Comment by SteffenCzolbe** [comment]
During the optimization of the LDDMM algorithm, the (time-indexed) forward transformation is saved in variable Phi0. it is then applied to image I0, and the transformed image is saved in J0. See the relevant code:

https://github.com/SteffenCzolbe/pyLDDMM/blob/72457581ec5cdc82f312b4396c7a7214149525b5/pyLDDMM/LDDMM.py#L49-L53

After optimization, the final transformation Phi0 is returned by the registration function linked above. To apply this transformation to a new image, you need to sample the image, similar to what is done during the push-forward step:

https://github.com/SteffenCzolbe/pyLDDMM/blob/72457581ec5cdc82f312b4396c7a7214149525b5/pyLDDMM/LDDMM.py#L182-L183

Except that instead of iterating over all timesteps t, the last timestep suffices for your use-case.

**Comment by SZUHvern** [comment]
It works. Sincerely thank you for your patient answers, which has helped me a lot.
